-- Seed de desenvolvimento é aplicado automaticamente via DataSeeder (Java).
-- Credenciais padrão (senhas seguem RN02):
--
--   admin@vibeu.edu  / Admin123   (ADMINISTRADOR)
--   org@vibeu.edu    / Org12345   (ORGANIZADOR)
--   part@vibeu.edu   / Part1234   (PARTICIPANTE)
